"""Add media delivery sessions statistics and source pacing

Revision ID: 564d5950669a
Revises: 39052d216250
"""
from alembic import op
import sqlalchemy as sa


revision = '564d5950669a'
down_revision = '39052d216250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_observations',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('elapsed_ms', sa.Float(), nullable=False),
    sa.Column('bytes_read', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['storage_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_observations_measured_at'), 'storage_observations', ['measured_at'], unique=False)
    op.create_index(op.f('ix_storage_observations_profile_id'), 'storage_observations', ['profile_id'], unique=False)
    op.create_index(op.f('ix_storage_observations_user_id'), 'storage_observations', ['user_id'], unique=False)
    op.create_table('video_stat_snapshots',
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'run_id')
    )
    op.create_index(op.f('ix_video_stat_snapshots_video_id'), 'video_stat_snapshots', ['video_id'], unique=False)
    op.create_index('ix_video_stats_observed', 'video_stat_snapshots', ['video_id', 'observed_at'], unique=False)
    op.create_table('playback_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['storage_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['media_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playback_sessions_expires_at'), 'playback_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_playback_sessions_user_id'), 'playback_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_playback_sessions_variant_id'), 'playback_sessions', ['variant_id'], unique=False)
    # Existing archives must migrate without losing rows or receiving SQL NULL.
    op.add_column('media_variants', sa.Column('metadata_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('source_accounts', sa.Column('next_request_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('source_accounts', sa.Column('next_video_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('source_accounts', sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('source_accounts', sa.Column('risk_failures', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_accounts', 'risk_failures')
    op.drop_column('source_accounts', 'cooldown_until')
    op.drop_column('source_accounts', 'next_video_at')
    op.drop_column('source_accounts', 'next_request_at')
    op.drop_column('media_variants', 'metadata_json')
    op.drop_index(op.f('ix_playback_sessions_variant_id'), table_name='playback_sessions')
    op.drop_index(op.f('ix_playback_sessions_user_id'), table_name='playback_sessions')
    op.drop_index(op.f('ix_playback_sessions_expires_at'), table_name='playback_sessions')
    op.drop_table('playback_sessions')
    op.drop_index('ix_video_stats_observed', table_name='video_stat_snapshots')
    op.drop_index(op.f('ix_video_stat_snapshots_video_id'), table_name='video_stat_snapshots')
    op.drop_table('video_stat_snapshots')
    op.drop_index(op.f('ix_storage_observations_user_id'), table_name='storage_observations')
    op.drop_index(op.f('ix_storage_observations_profile_id'), table_name='storage_observations')
    op.drop_index(op.f('ix_storage_observations_measured_at'), table_name='storage_observations')
    op.drop_table('storage_observations')
    # ### end Alembic commands ###
